# Ver o seguinte link --> https://pre-commit.com/

repos:
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'venv_docker/bin/pip3 freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]



    